add_rules("mode.debug")
-- add_rules("mode.debug", "mode.release")

add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
add_requires("doctest")

set_languages("c99", "cxx23")

toolchain("myclang")
    set_kind("standalone")
    set_sdkdir("C:/Users/cosette/scoop/apps/llvm-mingw/current")
    set_bindir("C:/Users/cosette/scoop/apps/llvm-mingw/current/bin")
    set_bindir("C:/Users/cosette/scoop/apps/llvm-mingw/current/x86_64-w64-mingw32/bin")
    add_includedirs("C:/Users/cosette/scoop/apps/llvm-mingw/current/include/c++/v1")
    add_includedirs("C:/Users/cosette/scoop/apps/llvm-mingw/current/include")
    add_linkdirs("C:/Users/cosette/scoop/apps/llvm-mingw/current/lib")
    add_linkdirs("C:/Users/cosette/scoop/apps/llvm-mingw/current/x86_64-w64-mingw32/lib")
    add_cxxflags("--target=x86_64-w64-mingw32", "-stdlib=libc++")
    add_shflags("--target=x86_64-w64-mingw32", "-stdlib=libc++")
    add_ldflags("--target=x86_64-w64-mingw32", "-stdlib=libc++", {force = true})
    set_toolset("cc", "clang")
    set_toolset("cxx", "clang", "clang++")
    set_toolset("ld", "clang++", "clang")
    set_toolset("sh", "clang++", "clang")
    set_toolset("ar", "ar")
    set_toolset("ex", "ar")
    set_toolset("strip", "strip")
    set_toolset("mm", "clang")
    set_toolset("mxx", "clang", "clang++")
    set_toolset("as", "clang")
toolchain_end()

set_toolchains("myclang")

includes("problems.xmake.lua")

